[package]
name = "dungeoncrawl"
authors = ["Praneeth Chinthaka Ranasinghe"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.bracket-lib]
version = "~0.8.1"

[dependencies.legion]
version = "=0.3.1"